__author__ = "Martin Rippin"
__copyright__ = "Copyright 2021, Martin Rippin"
__email__ = "martin.rippin@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/crumble.smk"
include: "rules/samtools.smk"
include: "rules/spring.smk"


rule all:
    input:
        unpack(compile_output_list),
