resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

reference:
  fasta: "reference/HES45.fasta"

default_container: "docker://hydragenetics/common:0.1.0"

crumble:
  container: "docker://hydragenetics/crumble:0.8.3"
  extra: "-O CRAM"

spring:
  container: "docker://hydragenetics/spring:1.0.1"
