from hydra_genetics.utils.resources import load_resources


rule all:
    input:
        "compression/spring/NA12878_N_HKTG2BGXG_L001_ACGGAACA+ACGAGAAC.spring",
        "compression/crumble/NA12878_N.crumble.cram",


configfile: "config.yaml"


config = load_resources(config, config["resources"])


def extract_module_version_from_readme(modulename):
    search_string = modulename + ":(.+)\n$"
    with open("../../README.md", "r") as reader:
        for line in reader:
            result = re.search(search_string, line)
            if result:
                return result[1]


module alignment:
    snakefile:
        github(
            "hydra-genetics/alignment",
            path="workflow/Snakefile",
            tag=extract_module_version_from_readme("alignment"),
        )
    config:
        config


use rule * from alignment as alignment_*


module compression:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config


use rule * from compression as compression_*
